### ISSUE TITLE
Error page not working on Laravel 9

### ISSUE THREAD

**Issue by zolotov88** [tarampampam/laravel-roadrunner-in-docker#116]
Error page not working on Laravel 9. JS error. With php artisan serve it's ok.

**Comment by tarampampam** [comment]
Hi @zolotov88!

How I can reproduce the error? Locally all works fine on my machine:

![Снимок экрана в 2022-02-11 10-01-38](https://user-images.githubusercontent.com/7326800/153540199-1b7b57f2-a258-4914-b628-101a314f3aa4.png)

And the error page does not contain any JS code (could you please attach the error message or a screenshot?):

![Снимок экрана в 2022-02-11 10-01-06](https://user-images.githubusercontent.com/7326800/153540220-f16af887-0106-4a33-b42d-882f07f0a512.png)

**Comment by tarampampam** [comment]
Closed due inactivity

**Comment by zolotov88** [comment]
I clone project. Install, init, up, then I makes this:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/11463586/153704877-c4c789b4-a08c-456b-88ba-9db5de4b069c.png">
And web container is falls.
Then I makes this:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/11463586/153704959-3db5c3c9-f6c3-442b-a278-bc9e9ef0ae8a.png">
and reup web container. 
And when Iwant to see https://github.com/spatie/laravel-ignition error page i see white page without nothing. HTML there must beendings with JS but it breakes wirth error.
<img width="422" alt="image" src="https://user-images.githubusercontent.com/11463586/153705149-bb9a68f0-f4fc-45d7-9c0c-9247856ba70a.png">

**Comment by tarampampam** [comment]
Ok, thanks! I have found the mistake and it has been fixed here: https://github.com/spiral/roadrunner-laravel/pull/88

**Comment by tarampampam** [comment]
Please, update the package `spiral/roadrunner-laravel` - after that, all should be fine! Thank you for your report!

**Comment by zolotov88** [comment]
Thaknk you for very fast fix!
