### ISSUE TITLE
Front-end development/building

### ISSUE THREAD

**Issue by nitrogenium** [tarampampam/laravel-roadrunner-in-docker#24]
I'm looking forward to the description of front-end development/building. It will be extremely useful. 

Want to donate via patreon but couldn't make it :(

**Comment by tarampampam** [comment]
Dockerfile already contains basic instructions (commented) for frontend building:

https://github.com/tarampampam/laravel-roadrunner-in-docker/blob/743b39ce0595473adde90bccda191b50e6f4ff9e/Dockerfile#L3-L12

https://github.com/tarampampam/laravel-roadrunner-in-docker/blob/743b39ce0595473adde90bccda191b50e6f4ff9e/Dockerfile#L98-L99

What is needed else for you? Assets "watching" and shell to the container with available `node`?

**Comment by nitrogenium** [comment]
Did not see these lines in the docker file. Cool. That's what I'm doing now. 

(I thought there would be a whole manual that would teach me how to do it right.)  Thanks for sharing your work.
