### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by connerbw** [tarampampam/laravel-roadrunner-in-docker#27]
Thanks for the cool example.

Can you put a license file in the repo please?

Eg. https://github.com/spiral/roadrunner/blob/master/LICENSE

(Or similar?)

**Comment by tarampampam** [comment]
Because this repo based on [laravel skeleton](https://github.com/laravel/laravel) - the licence file is missing. When someone forks this repository - my name will be in the license file, which does not seem to be right..

**Comment by tarampampam** [comment]
License info added into the readme file, thank you for your issue :)
