### ISSUE TITLE
define domain

### ISSUE THREAD

**Issue by vahidalvandi** [tarampampam/laravel-roadrunner-in-docker#278]
Please indicate how the domain should be defined

**Comment by tarampampam** [comment]
Could you describe your problem first, please?

**Comment by vahidalvandi** [comment]
> Could you describe your problem first, please?

I did not see a place for domain settings, something that exists in ngnix, for example

**Comment by tarampampam** [comment]
Usually, in front of the app, something like nginx or traefik is used, which routes the traffic "domain <=> internal app IP". So, you want to expose the app to the external net without any proxy?

**Comment by vahidalvandi** [comment]
i want to expose app in domain.com

**Comment by vahidalvandi** [comment]
I think web server like nginx ?
