### ISSUE TITLE
make test-cover: su: unknown user <local username>

### ISSUE THREAD

**Issue by connerbw** [tarampampam/laravel-roadrunner-in-docker#28]
Where `dac.chartrand` is my username on OSX.

```
$ make test-cover

docker-compose run --rm --user "0:0" -e 'XDEBUG_MODE=coverage' app sh -c 'echo "XDebug installing, please wait.." \
		&& apk --no-cache add autoconf make g++ 1>/dev/null && pecl install xdebug-3.0.4 1>/dev/null \
		&& docker-php-ext-enable xdebug 1>/dev/null \
		&& su dac.chartrand -s /bin/sh -c "composer phpunit"'
Creating laravel-roadrunner-in-docker_app_run ... done
XDebug installing, please wait..
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
su: unknown user dac.chartrand
ERROR: 1
make: *** [test-cover] Error 1
```

**Comment by tarampampam** [comment]
I'm a Linux user, not OSX... Could you please execute:

```bash
grep dac.chartrand /etc/passwd # dac.chartrand is your username?
```

And show me your output?

**Comment by tarampampam** [comment]
Maybe you need to change this line:

https://github.com/tarampampam/laravel-roadrunner-in-docker/blob/f50ac94e5191f792febdbe58f1ba18128c3cba69/docker-compose.yml#L26

To the something like `/Users/dac.chartrand/templates/mac_passwd:/etc/passwd:ro`?

Similar issue: https://github.com/databio/bulker/issues/30#issuecomment-566169462

**Comment by connerbw** [comment]
> I'm a Linux user, not OSX... Could you please execute:
> `grep dac.chartrand /etc/passwd # dac.chartrand is your username?`
>  And show me your output?

It's empty.

> Similar issue: databio/bulker#30 (comment)

I was able to fix the problem based on the information found on that webpage:

> How can I make bulker retain my user ID on MacOS? If you're getting messages like 'I have no name!" using docker containers on MacOS, this is because MacOS doesn't use the traditional unix user system (using etc/passwd for users) unless it is operating in single-user mode. Instead, it uses a system called Open Directory DirectoryService. See this stackoverflow question for more information [1]. To accommodate this, if you're using MacOS outside of single-user mode, bulker has a script called fix_mac_user.sh [2]. If you run this script, it will create a temporary mapping that plays nice with the /etc/passwd system required by the containers, and will correctly map your user.

Sources:

[0] https://bulker.databio.org/en/dev/tips/
[1] https://superuser.com/questions/191330/users-dont-appear-in-etc-passwd-on-mac-os-x/191333#191333
[2] https://github.com/databio/bulker/blob/master/fix_mac_user.sh

This is my version of the script, I put `./fix_mac_user.sh` put in the root dir of this project:

```bash
#!/bin/sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR
echo "$USER:x:$(id -u):$(id -g):ns,,,:$HOME:/bin/bash" > mac_passwd
sed -i.backup 's~/etc/passwd:/etc/passwd:ro~./mac_passwd:/etc/passwd:ro~' docker-compose.yml
```

**Comment by tarampampam** [comment]
This is a very sad story.. Could you please close this issue?
