### ISSUE TITLE
using dump() in source code doesn't print out anything

### ISSUE THREAD

**Issue by lanphan** [tarampampam/laravel-roadrunner-in-docker#55]
Hello,

I tried to add `dump('aaa')` into the first line of TestController#database() method, restart containers, and run again, but I don't see any 'aaa' message print out.

Besides that, I installed package Laravel Dump Server https://beyondco.de/docs/laravel-dump-server but seems it cannot capture dump message.

Would you please take a look and tell me how to enable dump() in laravel-roadrunner application?

Thanks so much.

**Comment by lanphan** [comment]
I also tried `\rr\dump('aaa')` but still not work

**Comment by tarampampam** [comment]
Hi @lanphan! I have found an error in the `spiral/roadrunner-laravel` package and fixed it. After [updating the package](https://github.com/spiral/roadrunner-laravel/releases/tag/v5.2.1) all should work fine, thanks for your issue!
