### ISSUE TITLE
I got error when run this docker on windows, can this docker run on windows ? 

### ISSUE THREAD

**Issue by NguyenDinhKhoi** [tarampampam/laravel-roadrunner-in-docker#79]
![image](https://user-images.githubusercontent.com/37110331/136411709-f5253500-6422-40b5-bf34-ed3545cbdaf6.png)

**Comment by tarampampam** [comment]
This issue can be closed?

**Comment by NguyenDinhKhoi** [comment]
Okay, thank you for your support
